#  this is the example of case_file
#  .toml format
[main]
in = ">>><<><>><<<>><>>><<<>>><<<><<<>><>><<>>"
out = "3068"                                    # output may not be specified - "?"
time = 1000
