#  this is the example of case_file
#  .toml format
[main]
in = """
......#.##.###.###..##...#.###..###....##....#.#.#.#...#.#..#####.#..#.#..
#######.##...##.##..#..##.#....#.###.##...#...##......######...#...###..#.
...#.#.##.#.##.#.#..#..#.#.##.######...###.....#.#.##..##..##.#..####..###
.##.#.##.#.#.#..#.##.###..........###..#.##.....#..#####.#....#.##...#..##
#.#...###...#.##.....#####.#.#.###..##.#...#..#.#.###.##......#.###.#####.
....##....#####..##.#....#.##.#.##....##.####..#.##...#..##..#.##....#.##.
.......##.#..#..##...####.##.#..###.....##.##...#.....###.###...#....#....
.####.##.##..#...##.##...###..####..####....#####.###.####....###.###.#...
####..##.#..##.###...####..#####....#.####.............##.###.......#....#
..........#...##....#.#####..#....##.###...####...##..###.##.#.##......###
.........#.#.##.##..#.#.####.#.##.#.##..#...##..##...#.#####...##.#..#..#.
##..#...#..#.###.###..#....##.#......###...#.#...#.#.##...#####..##.###...
.##.##......#.####..#..#...#.#..##..##..#..##..###.#.##.....#..##.###.#.#.
.############...#.#.##..##...........#.######.#..####.####...###..#.#.#.#.
#...##..##.....###.#...##..##..##.....#...#..###..###..####.#.#..#.##..###
#...##.#.#..##.###.#.....####.#.#...#....#####.##...#.#.###....#.#.#.#..##
##.###..####.....#####..###.##..###..#####.#.#####.#.#...#.#...###.###.###
####...#.####..#.#.##..#..#..##..##.#.........#.#..##.####.###......#...##
#....##.####.##.#.#.#.##.##..##.##.#.#.#......#.####.##..#..##..#..##..#..
..##...##.#.###.##..##.#..##.......#.####.#...#...#.#...###...#..####..###
##.#..####..#.#.##.##..#.##..##.......####...######.######...#....#.......
##....##.####..###.....####..###.#..#.######.##..###.#..##...#.###..#.###.
.####.#.###########..###........#.#.##.##.###...#.##.#..###.#.#.....#####.
##.#.###..##....###...##.##....##.#.#..#.###.##..#.#...###...####.##..###.
.#.#.#.###.#.###.....#..#.#######.......#.#.#.#######..####.#..###.#...#.#
#..##..##.#.#.#.##....#.#.###.#..##.##..##.####.#.#.#.........##.#.#....##
###..#.#...#...##.###...#..#.#.#.#.###..#.###...#.#.###.######.##.##....##
#.#....#.###.#.##..#...#..###.####..#.##..#.#.#.##...###...#.##..#.#.#####
.....#.#.....#.###.#.##.#...#....##.#.#.#..#.#####.##..#.#..##.#.#####..##
...#......#.###.###...####..####...##...####.###.##...#...#######..#..##..
##.....#...####.#.#...#...#..##..#...#####.##.#..#....##.###.##....#.#.###
#.####.#..##.#####.##..###.#..........###..#...#.#..##.#..####.....#......
....#.###.....#...#.#.##.##...####..##.#.##.#...###.#####.#..#.##.#.....##
#.###.#....#..#.###..#..##..######.##.#.#.###.#.#.##..##...#.##..#..##...#
###..####.##...#..#.##...#...#...###.###..###.#...#..##.#.#.###..##.#..##.
#.##.###..#....#....#..#.##.......###.###.#.###.##......#####..#...###.###
#.#.#..#..#.#######.##..#....##....#.###.##...##...#..#.####.#.##..#....#.
##..##.###.#..#.#..#.#.#.#..#.##.###.#.##..##...###########..###.#.#..###.
..#..##..##########...#########.#.#.#......###......#.....#....##..######.
.#.#...#..#..#....#.#.#...##..##.##.#....##....#..#...##..#.##...#...##.#.
##..#.#.#.####...##.####..###....#.#.##.#.#...#.##.#...######.##..#####.#.
#.#..###...#..##..###.#.#.#..#..#.#.#...#.##.#....#...##.###.##.#..##.#..#
#...#..##..#...#......####....#.#.##..#.##.###..##.##.#..#.#####.##.#.####
.####....##.#..####..##.#..#.#.######.####..##.......###...#####.....#....
..#..##.#.#..#####...##.#....####...##.#.#.###.#.##.#..#.###..###.##..##..
###..###.##.#.......##...##..#..#.#..#.#.##..#.####.#.##..#.##.###.##..###
#.....######.#...##...#.#.#####..#.######.....#..#..###..#.###....###..###
#...##....###..#.#.##..#.###.##..####.#..#...#.#....##.#.####...#####.#.#.
#.#.#...##.#######....#..###..####.#.#####....###.##.#...#.#####.#...###.#
####.#......#..#.#.##.####....#.#.##.#...#...##..#........###.###.##.#...#
#####..##..##.#####....#.#.#..#.##......##.##...#.#...#.####.#.##.#####.##
.#.#.####..##...#...#..##..#.#..###...#...#######..##.#####..#..#..#....##
###.....###..##.#..#####.#..#...###.##.##.###..#....#.....##.#.#.###...###
..#...######..##.#.#.#.########.###....#...#.##...#..##.#.##..###...#.###.
##..#....##..########.###..#..#.##..#######.#.#..#.#.##..##.#...##....#..#
#.##..#....###...#.##..#.#.#..#.....#...####....####..##..#..#..#..#.##.#.
##...#...#.#..#...#..####.#...##..#..###.##.....#.##.##..#.##.##.#..#.####
####....####.##...#.##..#...##...#.##.####.....###.#.#.###...#.##.##.##.##
#...#.#....#.#.#####.##.#.##.#...#.##.#...#...#.##..##...#...#..#...#..##.
#..####.#..#...##.#.####..###...##.###.#######...#.....#..#.#####..##..##.
##.#...##..###########.....##.##..#...#.####....#.#....####.##.#.###.#.##.
#...#..#.#####.#....#.##..###...#..#...#######.#...##..#..#.###..#.##.#..#
###.##...#.####....##.########......#...#...####.#..####.##.##..##..##....
##..###..#####...###..#.#...#..###....###.#..###....#.......#.###.#.#.#.##
........#.#....#..#.#...#...#####.####.....###...##.#.#...#.#..###...##..#
#.....###.####....###.#.##.##.#.##..#.#...##..##.....#.#..#.###.##.#......
..#...##.#..###.###..#..##...#.#..#.#####.##..##..#..#.....#####.######..#
...#...##.#.#......###.####..#.##...#..#....##.#.####..#.#..#...#.##.#..#.
.#.....##.#..####.###.#.#...#..#...#.##.#.#.#.####.##...#..###..####.#####
..##..##.#.##......#.#.####.#####.#.##..###.##........#....#..#.#..##.##..
..##..##...#..###...#..#.#...#.....###...##..###.###..##.#.#....#..#..##..
##.#..#.#.###....###..##...###.##.#..#####..##..##..#.......##..#.###..#..
#..#.###.###.##.###.###....#..#..##.##.#.#.##.#.#....##.#..#.#.###.##.###.
.##.#..#.###....##.####.##........#..####..#..#.....#.##..#.#..#..###.#..#
"""
out = "?" # output may not be specified - "?"
time = 40
