#  this is the example of case_file
#  .toml format
[main]
in = """
498,4 -> 498,6 -> 496,6
503,4 -> 502,4 -> 502,9 -> 494,9
"""
out = "93" # output may not be specified - "?"

example = """
  4444445  5
  9999990  0
  4567890  3
0 ......+...
1 ..........
2 ..........
3 ..........
4 ....#...##
5 ....#...#.
6 ..###...#.
7 ........#.
8 ........#.
9 #########.
"""
